name = "ejbtrdmcpack"
author = "ejbtrd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b164a3224de74c72b5b8a71976a327bb227621b6acfcddc6806229cbd4cabbdb"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
