name = "ejbtrdmcpack"
author = "ejbtrd"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4735b4565fed526a441bc13ee62fc17241dbb654f0a0064e8c69de7d20445d3c"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
